- name: Web Server Deployment
  hosts: webserver
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Allow HTTP through UFW
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes